services:
  db:
    image: postgres:17-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: bofa
      POSTGRES_PASSWORD: bofa_wex_2025
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432